[yagp_hooks_collector] Add --with-yagp-hooks-collector configure option and CI
Add configure.ac option with protobuf dependency.  Add CI test
configuration.  Change env script from greenplum_path.sh to
cloudberry-env.sh.

diff --git a/.github/workflows/build-cloudberry.yml b/.github/workflows/build-cloudberry.yml
--- a/.github/workflows/build-cloudberry.yml
+++ b/.github/workflows/build-cloudberry.yml
@@ -279,6 +279,9 @@ jobs:
               {"test":"gpcontrib-gp-stats-collector",
                "make_configs":["gpcontrib/gp_stats_collector:installcheck"],
                "extension":"gp_stats_collector"
+              {"test":"gpcontrib-yagp-hooks-collector",
+               "make_configs":["gpcontrib/yagp_hooks_collector:installcheck"],
+               "extension":"yagp_hooks_collector"
               },
               {"test":"ic-expandshrink",
                "make_configs":["src/test/isolation2:installcheck-expandshrink"]
@@ -552,10 +555,11 @@ jobs:
         if: needs.check-skip.outputs.should_skip != 'true'
         env:
           SRC_DIR: ${{ github.workspace }}
+          CONFIGURE_EXTRA_OPTS: --with-yagp-hooks-collector
         run: |
           set -eo pipefail
           chmod +x "${SRC_DIR}"/devops/build/automation/cloudberry/scripts/configure-cloudberry.sh
-          if ! time su - gpadmin -c "cd ${SRC_DIR} && SRC_DIR=${SRC_DIR} ENABLE_DEBUG=${{ env.ENABLE_DEBUG }} ${SRC_DIR}/devops/build/automation/cloudberry/scripts/configure-cloudberry.sh"; then
+          if ! time su - gpadmin -c "cd ${SRC_DIR} && SRC_DIR=${SRC_DIR} ENABLE_DEBUG=${{ env.ENABLE_DEBUG }} CONFIGURE_EXTRA_OPTS=${{ env.CONFIGURE_EXTRA_OPTS }} ${SRC_DIR}/devops/build/automation/cloudberry/scripts/configure-cloudberry.sh"; then
             echo "::error::Configure script failed"
             exit 1
           fi
@@ -1459,6 +1463,12 @@ jobs:
                   gpconfig -c shared_preload_libraries -v 'gp_stats_collector' && \
                   gpstop -ra && \
                   echo 'CREATE EXTENSION IF NOT EXISTS gp_stats_collector; \
+              yagp_hooks_collector)
+                if ! su - gpadmin -c "source ${BUILD_DESTINATION}/cloudberry-env.sh && \
+                  source ${SRC_DIR}/gpAux/gpdemo/gpdemo-env.sh && \
+                  gpconfig -c shared_preload_libraries -v 'yagp_hooks_collector' && \
+                  gpstop -ra && \
+                  echo 'CREATE EXTENSION IF NOT EXISTS yagp_hooks_collector; \
                         SHOW shared_preload_libraries; \
                         TABLE pg_extension;' | \
                     psql postgres"
@@ -1478,6 +1488,7 @@ jobs:
                     psql postgres"
                 then
                     echo "Error creating gp_relaccess_stats extension"
+                    echo "Error creating yagp_hooks_collector extension"
                     exit 1
                 fi
                 ;;
