add: pgqs tests

diff --git a/.github/workflows/build-cloudberry.yml b/.github/workflows/build-cloudberry.yml
--- a/.github/workflows/build-cloudberry.yml
+++ b/.github/workflows/build-cloudberry.yml
@@ -271,6 +271,11 @@ jobs:
                 },
                 "enable_core_check":false
               },
+              {"test":"gpcontrib-gp-relaccess-stats",
+               "make_configs":["gpcontrib/gp_relaccess_stats:installcheck"],
+               "extension":"gp_relaccess_stats",
+               "shared_preload_libraries":"gp_relaccess_stats"
+              },
               {"test":"gpcontrib-gp-stats-collector",
                "make_configs":["gpcontrib/gp_stats_collector:installcheck"],
                "extension":"gp_stats_collector"
@@ -1459,6 +1464,20 @@ jobs:
                     psql postgres"
                 then
                     echo "Error creating gp_stats_collector extension"
+                    exit 1
+                fi
+                ;;
+              gp_relaccess_stats)
+                if ! su - gpadmin -c "source ${BUILD_DESTINATION}/cloudberry-env.sh && \
+                  source ${SRC_DIR}/gpAux/gpdemo/gpdemo-env.sh && \
+                  gpconfig -c shared_preload_libraries -v 'gp_relaccess_stats' && \
+                  gpstop -ra && \
+                  echo 'CREATE EXTENSION IF NOT EXISTS gp_relaccess_stats; \
+                        SHOW shared_preload_libraries; \
+                        TABLE pg_extension;' | \
+                    psql postgres"
+                then
+                    echo "Error creating gp_relaccess_stats extension"
                     exit 1
                 fi
                 ;;
